#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
if [[ ! -f "apache-access.log" ]]; then
    echo "Error: apache-access.log not found."
    exit 1
fi
awk '{print $1, $9}' apache-access.log
