#!/usr/bin/env bash
# Script that prints "Best School" 10 times, adding "Hi" on the 9th turn
i=1
while [ "$i" -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done
